name: Sync to Hugging Face Hub

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "sync-bot@example.com"
          git config --global user.name "Sync Bot"
          git checkout --orphan deploy-branch
          git add .
          git commit -m "Deploy to Hugging Face"
          git push https://Ekrash1234:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Ekrash1234/github_deploy_token deploy-branch:main -f
